# Generated by Django 3.1.4 on 2021-01-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210101_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='year',
            field=models.IntegerField(default=1999),
        ),
    ]
