# Generated by Django 3.1.4 on 2021-01-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210114_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='collection.company'),
        ),
    ]
