name: Deploy

on:
  workflow_run:
    workflows: [ 'Test' ]
    branches: [ 'main' ]
    types:
      - completed

jobs:
  pipeline-component:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        shell: bash
        run: |
          ls -la .github/scripts
          pwd
          ./github/scripts/deploy.sh
        env:
          DEPLOY_USER: ${{ secrets.DeployUser }}
          DEPLOY_PASS: ${{ secrets.DeployPass }}
          DEPLOY_HOST: ${{ secrets.DeployHost }}
          DEPLOY_PATH: ${{ secrets.DeployPath }}
          DEPLOY_SCRIPT_PATH: ${{ secrets.DeployScriptPath }}

